//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingspModel.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 可使用英文(a-z)、數字(0-9)和底線(_)。 的當地語系化字串。
        /// </summary>
        public static string AccountLimit {
            get {
                return ResourceManager.GetString("AccountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增使用者 的當地語系化字串。
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每頁顯示&lt;input type=&apos;text&apos; name=&apos;defaultPage&apos; value=&apos;&apos; size=&apos;2&apos; onchange=&apos;InputGo($(this).val())&apos; /&gt;筆&lt;/span&gt;&lt;input type=&apos;button&apos; class=&apos;btn&apos; value=&apos;顯示&apos; title=&apos;顯示&apos; onclick=&apos;ChangeDefaultPage()&apos;/&gt; 的當地語系化字串。
        /// </summary>
        public static string AdminListPage {
            get {
                return ResourceManager.GetString("AdminListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;span style=\&quot;line-height:30px\&quot;&gt;總共 {0} 頁 / {1} 筆資料&lt;/span&gt; 的當地語系化字串。
        /// </summary>
        public static string AdminTotalPage {
            get {
                return ResourceManager.GetString("AdminTotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查看全部 的當地語系化字串。
        /// </summary>
        public static string all1 {
            get {
                return ResourceManager.GetString("all1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 擇一填寫 的當地語系化字串。
        /// </summary>
        public static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 審核狀態 的當地語系化字串。
        /// </summary>
        public static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未通過 的當地語系化字串。
        /// </summary>
        public static string ApprovalStatus_DidNotPass {
            get {
                return ResourceManager.GetString("ApprovalStatus_DidNotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通過 的當地語系化字串。
        /// </summary>
        public static string ApprovalStatus_Pass {
            get {
                return ResourceManager.GetString("ApprovalStatus_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待審核 的當地語系化字串。
        /// </summary>
        public static string ApprovalStatus_PendingReview {
            get {
                return ResourceManager.GetString("ApprovalStatus_PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回上頁 的當地語系化字串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回上一頁 的當地語系化字串。
        /// </summary>
        public static string back1 {
            get {
                return ResourceManager.GetString("back1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回主頁 的當地語系化字串。
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 瀏覽 的當地語系化字串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不能為空 的當地語系化字串。
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺北市 的當地語系化字串。
        /// </summary>
        public static string City1 {
            get {
                return ResourceManager.GetString("City1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 南投縣 的當地語系化字串。
        /// </summary>
        public static string City10 {
            get {
                return ResourceManager.GetString("City10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 雲林縣 的當地語系化字串。
        /// </summary>
        public static string City11 {
            get {
                return ResourceManager.GetString("City11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 花蓮縣 的當地語系化字串。
        /// </summary>
        public static string City12 {
            get {
                return ResourceManager.GetString("City12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嘉義市 的當地語系化字串。
        /// </summary>
        public static string City13 {
            get {
                return ResourceManager.GetString("City13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嘉義縣 的當地語系化字串。
        /// </summary>
        public static string City14 {
            get {
                return ResourceManager.GetString("City14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺南市 的當地語系化字串。
        /// </summary>
        public static string City15 {
            get {
                return ResourceManager.GetString("City15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高雄市 的當地語系化字串。
        /// </summary>
        public static string City16 {
            get {
                return ResourceManager.GetString("City16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺東縣 的當地語系化字串。
        /// </summary>
        public static string City17 {
            get {
                return ResourceManager.GetString("City17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 屏東縣 的當地語系化字串。
        /// </summary>
        public static string City18 {
            get {
                return ResourceManager.GetString("City18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基隆市 的當地語系化字串。
        /// </summary>
        public static string City2 {
            get {
                return ResourceManager.GetString("City2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新北市 的當地語系化字串。
        /// </summary>
        public static string City3 {
            get {
                return ResourceManager.GetString("City3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桃園市 的當地語系化字串。
        /// </summary>
        public static string City4 {
            get {
                return ResourceManager.GetString("City4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 宜蘭縣 的當地語系化字串。
        /// </summary>
        public static string City5 {
            get {
                return ResourceManager.GetString("City5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新竹縣 的當地語系化字串。
        /// </summary>
        public static string City6 {
            get {
                return ResourceManager.GetString("City6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 苗栗縣 的當地語系化字串。
        /// </summary>
        public static string City7 {
            get {
                return ResourceManager.GetString("City7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺中市 的當地語系化字串。
        /// </summary>
        public static string City8 {
            get {
                return ResourceManager.GetString("City8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 彰化縣 的當地語系化字串。
        /// </summary>
        public static string City9 {
            get {
                return ResourceManager.GetString("City9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員帳號 的當地語系化字串。
        /// </summary>
        public static string code01 {
            get {
                return ResourceManager.GetString("code01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紅利點數 的當地語系化字串。
        /// </summary>
        public static string code02 {
            get {
                return ResourceManager.GetString("code02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單管理 的當地語系化字串。
        /// </summary>
        public static string code03 {
            get {
                return ResourceManager.GetString("code03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用條款 的當地語系化字串。
        /// </summary>
        public static string code04 {
            get {
                return ResourceManager.GetString("code04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客服相關 的當地語系化字串。
        /// </summary>
        public static string code05 {
            get {
                return ResourceManager.GetString("code05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 水資源 的當地語系化字串。
        /// </summary>
        public static string code06 {
            get {
                return ResourceManager.GetString("code06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自然生態 的當地語系化字串。
        /// </summary>
        public static string code07 {
            get {
                return ResourceManager.GetString("code07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 食農教育 的當地語系化字串。
        /// </summary>
        public static string code08 {
            get {
                return ResourceManager.GetString("code08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人文歷史 的當地語系化字串。
        /// </summary>
        public static string code09 {
            get {
                return ResourceManager.GetString("code09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 環保再生 的當地語系化字串。
        /// </summary>
        public static string code10 {
            get {
                return ResourceManager.GetString("code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 綠色節能 的當地語系化字串。
        /// </summary>
        public static string code11 {
            get {
                return ResourceManager.GetString("code11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 環境污染 的當地語系化字串。
        /// </summary>
        public static string code12 {
            get {
                return ResourceManager.GetString("code12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 防救災害 的當地語系化字串。
        /// </summary>
        public static string code13 {
            get {
                return ResourceManager.GetString("code13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 海洋 的當地語系化字串。
        /// </summary>
        public static string code14 {
            get {
                return ResourceManager.GetString("code14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 森林 的當地語系化字串。
        /// </summary>
        public static string code15 {
            get {
                return ResourceManager.GetString("code15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 農業 的當地語系化字串。
        /// </summary>
        public static string code16 {
            get {
                return ResourceManager.GetString("code16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歷史人文 的當地語系化字串。
        /// </summary>
        public static string code17 {
            get {
                return ResourceManager.GetString("code17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生態守護王 的當地語系化字串。
        /// </summary>
        public static string code18 {
            get {
                return ResourceManager.GetString("code18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已取消 的當地語系化字串。
        /// </summary>
        public static string code19 {
            get {
                return ResourceManager.GetString("code19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待使用 的當地語系化字串。
        /// </summary>
        public static string code20 {
            get {
                return ResourceManager.GetString("code20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已使用 的當地語系化字串。
        /// </summary>
        public static string code21 {
            get {
                return ResourceManager.GetString("code21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司名稱 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT1 {
            get {
                return ResourceManager.GetString("Company_CONTENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT10 {
            get {
                return ResourceManager.GetString("Company_CONTENT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網站 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT11 {
            get {
                return ResourceManager.GetString("Company_CONTENT11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FB 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT12 {
            get {
                return ResourceManager.GetString("Company_CONTENT12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IG 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT13 {
            get {
                return ResourceManager.GetString("Company_CONTENT13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 協會成員 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT2 {
            get {
                return ResourceManager.GetString("Company_CONTENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司簡介 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT3 {
            get {
                return ResourceManager.GetString("Company_CONTENT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地接旅行社 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT4 {
            get {
                return ResourceManager.GetString("Company_CONTENT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT5 {
            get {
                return ResourceManager.GetString("Company_CONTENT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT6 {
            get {
                return ResourceManager.GetString("Company_CONTENT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司所在地 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT7 {
            get {
                return ResourceManager.GetString("Company_CONTENT7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司地址 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT8 {
            get {
                return ResourceManager.GetString("Company_CONTENT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E-mail 的當地語系化字串。
        /// </summary>
        public static string Company_CONTENT9 {
            get {
                return ResourceManager.GetString("Company_CONTENT9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類型 的當地語系化字串。
        /// </summary>
        public static string Company_DATA_TYPE {
            get {
                return ResourceManager.GetString("Company_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司別 的當地語系化字串。
        /// </summary>
        public static string Company_STATUS {
            get {
                return ResourceManager.GetString("Company_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期範圍 的當地語系化字串。
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string define {
            get {
                return ResourceManager.GetString("define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請刪除公司下的使用者!! 的當地語系化字串。
        /// </summary>
        public static string DeleteCompanyUser {
            get {
                return ResourceManager.GetString("DeleteCompanyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 證書下載 的當地語系化字串。
        /// </summary>
        public static string DownloadCertificate {
            get {
                return ResourceManager.GetString("DownloadCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯使用者 的當地語系化字串。
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日 的當地語系化字串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文名稱 的當地語系化字串。
        /// </summary>
        public static string EnTitle {
            get {
                return ResourceManager.GetString("EnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件 的當地語系化字串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我要填寫 的當地語系化字串。
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 填寫日期 的當地語系化字串。
        /// </summary>
        public static string FillDate {
            get {
                return ResourceManager.GetString("FillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版權所有 © 2021 All Rights Reserved. 的當地語系化字串。
        /// </summary>
        public static string Footer_01 {
            get {
                return ResourceManager.GetString("Footer_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建議使用瀏覽器IE11.0以上版本；最佳螢幕解析度：1024x768 以上 的當地語系化字串。
        /// </summary>
        public static string Footer_02 {
            get {
                return ResourceManager.GetString("Footer_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新屋濱海植物園APP下載 的當地語系化字串。
        /// </summary>
        public static string footer_app {
            get {
                return ResourceManager.GetString("footer_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桃園市政府環境保護局 的當地語系化字串。
        /// </summary>
        public static string footer01 {
            get {
                return ResourceManager.GetString("footer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 33001桃園市桃園區縣府路1號11F 的當地語系化字串。
        /// </summary>
        public static string footer02 {
            get {
                return ResourceManager.GetString("footer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桃園市政府海岸管理工程處 的當地語系化字串。
        /// </summary>
        public static string footer03 {
            get {
                return ResourceManager.GetString("footer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 337017桃園市大園區中華路298號 的當地語系化字串。
        /// </summary>
        public static string footer04 {
            get {
                return ResourceManager.GetString("footer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最佳瀏覽環境1280x800視窗模式以上，IE11以上版本瀏覽器 的當地語系化字串。
        /// </summary>
        public static string footer05 {
            get {
                return ResourceManager.GetString("footer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於海岸管理工程處 的當地語系化字串。
        /// </summary>
        public static string footer06 {
            get {
                return ResourceManager.GetString("footer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 常見問題 的當地語系化字串。
        /// </summary>
        public static string footer07 {
            get {
                return ResourceManager.GetString("footer07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        public static string footer08 {
            get {
                return ResourceManager.GetString("footer08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 友站連結 的當地語系化字串。
        /// </summary>
        public static string footer09 {
            get {
                return ResourceManager.GetString("footer09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網站安全政策 的當地語系化字串。
        /// </summary>
        public static string footer10 {
            get {
                return ResourceManager.GetString("footer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組名稱 的當地語系化字串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組權限 的當地語系化字串。
        /// </summary>
        public static string GroupPermissions {
            get {
                return ResourceManager.GetString("GroupPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歡迎使用 的當地語系化字串。
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份 的當地語系化字串。
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 熱門 的當地語系化字串。
        /// </summary>
        public static string index01 {
            get {
                return ResourceManager.GetString("index01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生態體驗 的當地語系化字串。
        /// </summary>
        public static string index02 {
            get {
                return ResourceManager.GetString("index02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新 的當地語系化字串。
        /// </summary>
        public static string index03 {
            get {
                return ResourceManager.GetString("index03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 優惠 的當地語系化字串。
        /// </summary>
        public static string index04 {
            get {
                return ResourceManager.GetString("index04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 精選 的當地語系化字串。
        /// </summary>
        public static string index05 {
            get {
                return ResourceManager.GetString("index05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遊程 的當地語系化字串。
        /// </summary>
        public static string index06 {
            get {
                return ResourceManager.GetString("index06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送客資料 的當地語系化字串。
        /// </summary>
        public static string InformationDrop {
            get {
                return ResourceManager.GetString("InformationDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號、姓名、E-mail、公司名稱 的當地語系化字串。
        /// </summary>
        public static string Keyword_SYSUSER {
            get {
                return ResourceManager.GetString("Keyword_SYSUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後登入時間 的當地語系化字串。
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;li class=&quot;all&quot;&gt;{0} 筆資料 / 每頁顯示 {1} 筆&lt;/li&gt; 的當地語系化字串。
        /// </summary>
        public static string ListPage {
            get {
                return ResourceManager.GetString("ListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用社交平臺快速登入 的當地語系化字串。
        /// </summary>
        public static string login_msg {
            get {
                return ResourceManager.GetString("login_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員帳號登入 的當地語系化字串。
        /// </summary>
        public static string login_msg1 {
            get {
                return ResourceManager.GetString("login_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入會員，隨時收到獨家優惠 的當地語系化字串。
        /// </summary>
        public static string login_msg10 {
            get {
                return ResourceManager.GetString("login_msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 免費註冊 的當地語系化字串。
        /// </summary>
        public static string login_msg2 {
            get {
                return ResourceManager.GetString("login_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員登入 的當地語系化字串。
        /// </summary>
        public static string login_msg3 {
            get {
                return ResourceManager.GetString("login_msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E-mail(帳號) 的當地語系化字串。
        /// </summary>
        public static string login_msg4 {
            get {
                return ResourceManager.GetString("login_msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string login_msg5 {
            get {
                return ResourceManager.GetString("login_msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘記密碼 的當地語系化字串。
        /// </summary>
        public static string login_msg6 {
            get {
                return ResourceManager.GetString("login_msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我已詳閱並同意 的當地語系化字串。
        /// </summary>
        public static string login_msg7 {
            get {
                return ResourceManager.GetString("login_msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證碼 的當地語系化字串。
        /// </summary>
        public static string login_msg8 {
            get {
                return ResourceManager.GetString("login_msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新產生 的當地語系化字串。
        /// </summary>
        public static string login_msg9 {
            get {
                return ResourceManager.GetString("login_msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號設定 的當地語系化字串。
        /// </summary>
        public static string member01 {
            get {
                return ResourceManager.GetString("member01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名 的當地語系化字串。
        /// </summary>
        public static string member02 {
            get {
                return ResourceManager.GetString("member02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓 的當地語系化字串。
        /// </summary>
        public static string member03 {
            get {
                return ResourceManager.GetString("member03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        public static string member04 {
            get {
                return ResourceManager.GetString("member04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出生日期 的當地語系化字串。
        /// </summary>
        public static string member05 {
            get {
                return ResourceManager.GetString("member05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼設定 的當地語系化字串。
        /// </summary>
        public static string member06 {
            get {
                return ResourceManager.GetString("member06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 E-mail(不可修改) 的當地語系化字串。
        /// </summary>
        public static string member07 {
            get {
                return ResourceManager.GetString("member07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的點數 的當地語系化字串。
        /// </summary>
        public static string member08 {
            get {
                return ResourceManager.GetString("member08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單查詢 的當地語系化字串。
        /// </summary>
        public static string member09 {
            get {
                return ResourceManager.GetString("member09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兌換紀錄查詢 的當地語系化字串。
        /// </summary>
        public static string member10 {
            get {
                return ResourceManager.GetString("member10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string member11 {
            get {
                return ResourceManager.GetString("member11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前點數 的當地語系化字串。
        /// </summary>
        public static string member12 {
            get {
                return ResourceManager.GetString("member12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兌換好禮 的當地語系化字串。
        /// </summary>
        public static string member13 {
            get {
                return ResourceManager.GetString("member13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 守護者經驗 的當地語系化字串。
        /// </summary>
        public static string member14 {
            get {
                return ResourceManager.GetString("member14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 見習守護者 的當地語系化字串。
        /// </summary>
        public static string member15 {
            get {
                return ResourceManager.GetString("member15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進階守護者 的當地語系化字串。
        /// </summary>
        public static string member16 {
            get {
                return ResourceManager.GetString("member16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資深守護者 的當地語系化字串。
        /// </summary>
        public static string member17 {
            get {
                return ResourceManager.GetString("member17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 菁英守護者 的當地語系化字串。
        /// </summary>
        public static string member18 {
            get {
                return ResourceManager.GetString("member18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳奇守護者 的當地語系化字串。
        /// </summary>
        public static string member19 {
            get {
                return ResourceManager.GetString("member19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前累積經驗值 的當地語系化字串。
        /// </summary>
        public static string member20 {
            get {
                return ResourceManager.GetString("member20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單編號 的當地語系化字串。
        /// </summary>
        public static string member21 {
            get {
                return ResourceManager.GetString("member21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購買日期 的當地語系化字串。
        /// </summary>
        public static string member22 {
            get {
                return ResourceManager.GetString("member22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 至Kkday查詢詳細內容 的當地語系化字串。
        /// </summary>
        public static string member23 {
            get {
                return ResourceManager.GetString("member23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兌換紀錄 的當地語系化字串。
        /// </summary>
        public static string member24 {
            get {
                return ResourceManager.GetString("member24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點數紀錄 的當地語系化字串。
        /// </summary>
        public static string member25 {
            get {
                return ResourceManager.GetString("member25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到期 的當地語系化字串。
        /// </summary>
        public static string member26 {
            get {
                return ResourceManager.GetString("member26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動訊息 的當地語系化字串。
        /// </summary>
        public static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 環境教育場域 的當地語系化字串。
        /// </summary>
        public static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 熱門景點 的當地語系化字串。
        /// </summary>
        public static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生態遊程 的當地語系化字串。
        /// </summary>
        public static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人氣商家 的當地語系化字串。
        /// </summary>
        public static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好禮兌換 的當地語系化字串。
        /// </summary>
        public static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員專區 的當地語系化字串。
        /// </summary>
        public static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於本站 的當地語系化字串。
        /// </summary>
        public static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務條款 的當地語系化字串。
        /// </summary>
        public static string menu09 {
            get {
                return ResourceManager.GetString("menu09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PROGRAM RULES 的當地語系化字串。
        /// </summary>
        public static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ITINERARIES 的當地語系化字串。
        /// </summary>
        public static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RESOURCES 的當地語系化字串。
        /// </summary>
        public static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 REGISTER BOOKINGS 的當地語系化字串。
        /// </summary>
        public static string Menu4 {
            get {
                return ResourceManager.GetString("Menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WINNERS 的當地語系化字串。
        /// </summary>
        public static string Menu5 {
            get {
                return ResourceManager.GetString("Menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu6 {
            get {
                return ResourceManager.GetString("Menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更多 的當地語系化字串。
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 再一次確認，您要刪除這筆資料？ 的當地語系化字串。
        /// </summary>
        public static string msg_01 {
            get {
                return ResourceManager.GetString("msg_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼錯誤!! 請確認帳號和密碼的大小寫是否一致!!  的當地語系化字串。
        /// </summary>
        public static string msg_02 {
            get {
                return ResourceManager.GetString("msg_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問卷已被使用，無法刪除。 的當地語系化字串。
        /// </summary>
        public static string msg_03 {
            get {
                return ResourceManager.GetString("msg_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已刪除 的當地語系化字串。
        /// </summary>
        public static string msg_04 {
            get {
                return ResourceManager.GetString("msg_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除失敗 的當地語系化字串。
        /// </summary>
        public static string msg_05 {
            get {
                return ResourceManager.GetString("msg_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您答錯了喔!! 的當地語系化字串。
        /// </summary>
        public static string msg_06 {
            get {
                return ResourceManager.GetString("msg_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊成功，請至您註冊時填寫的電子信箱收信，並點擊信件中的超連結來啟用帳號。 的當地語系化字串。
        /// </summary>
        public static string msg_07 {
            get {
                return ResourceManager.GetString("msg_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已開通 的當地語系化字串。
        /// </summary>
        public static string msg_08 {
            get {
                return ResourceManager.GetString("msg_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開通失敗，請連絡管理員。 的當地語系化字串。
        /// </summary>
        public static string msg_09 {
            get {
                return ResourceManager.GetString("msg_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已啟用 的當地語系化字串。
        /// </summary>
        public static string msg_10 {
            get {
                return ResourceManager.GetString("msg_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已停用 的當地語系化字串。
        /// </summary>
        public static string msg_11 {
            get {
                return ResourceManager.GetString("msg_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 如果清單中找不到您的公司，請自行輸入。 的當地語系化字串。
        /// </summary>
        public static string msg_12 {
            get {
                return ResourceManager.GetString("msg_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立您的帳戶 的當地語系化字串。
        /// </summary>
        public static string msg_14 {
            get {
                return ResourceManager.GetString("msg_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動時間內註冊自動報名 的當地語系化字串。
        /// </summary>
        public static string msg_15 {
            get {
                return ResourceManager.GetString("msg_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已開通，請自行前往登入頁。 的當地語系化字串。
        /// </summary>
        public static string msg_16 {
            get {
                return ResourceManager.GetString("msg_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要停用此帳號? 的當地語系化字串。
        /// </summary>
        public static string msg_17 {
            get {
                return ResourceManager.GetString("msg_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要啟用此帳號? 的當地語系化字串。
        /// </summary>
        public static string msg_18 {
            get {
                return ResourceManager.GetString("msg_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案類型錯誤，可接受的副檔名有： 的當地語系化字串。
        /// </summary>
        public static string msg_19 {
            get {
                return ResourceManager.GetString("msg_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳的檔案大小限制要低於 5MB 的當地語系化字串。
        /// </summary>
        public static string msg_20 {
            get {
                return ResourceManager.GetString("msg_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳的檔案只接受 pdf 和 word 的當地語系化字串。
        /// </summary>
        public static string msg_21 {
            get {
                return ResourceManager.GetString("msg_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的帳號尚未啟用，請至您註冊時填寫的電子信箱收取確認信 的當地語系化字串。
        /// </summary>
        public static string msg_22 {
            get {
                return ResourceManager.GetString("msg_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一題 的當地語系化字串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一頁 的當地語系化字串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料筆數 的當地語系化字串。
        /// </summary>
        public static string NumberOfData {
            get {
                return ResourceManager.GetString("NumberOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 或 的當地語系化字串。
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頁 的當地語系化字串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 任職公司 的當地語系化字串。
        /// </summary>
        public static string PickCompany {
            get {
                return ResourceManager.GetString("PickCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總公司 的當地語系化字串。
        /// </summary>
        public static string PickThisStore {
            get {
                return ResourceManager.GetString("PickThisStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點 的當地語系化字串。
        /// </summary>
        public static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上一頁 的當地語系化字串。
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱私權保護政策 的當地語系化字串。
        /// </summary>
        public static string privacypolicy {
            get {
                return ResourceManager.GetString("privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理中 的當地語系化字串。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問卷統計 的當地語系化字串。
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問卷標題 的當地語系化字串。
        /// </summary>
        public static string QuestionnaireTitle {
            get {
                return ResourceManager.GetString("QuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歡迎參加臺灣旅遊專家培訓計畫 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG0 {
            get {
                return ResourceManager.GetString("QUIZ_MSG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 現在開始完成幾個簡單的基本測驗，就可以成為認證專家哦~ 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG1 {
            get {
                return ResourceManager.GetString("QUIZ_MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始測驗 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG2 {
            get {
                return ResourceManager.GetString("QUIZ_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 恭喜你已經是臺灣旅遊專家了，現在就開始上傳您的送客資料，成為金牌專家吧!! 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG3 {
            get {
                return ResourceManager.GetString("QUIZ_MSG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳資料 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG4 {
            get {
                return ResourceManager.GetString("QUIZ_MSG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成為臺灣旅遊專家 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG5 {
            get {
                return ResourceManager.GetString("QUIZ_MSG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳送客競賽資料 的當地語系化字串。
        /// </summary>
        public static string QUIZ_MSG6 {
            get {
                return ResourceManager.GetString("QUIZ_MSG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推薦 的當地語系化字串。
        /// </summary>
        public static string recommend {
            get {
                return ResourceManager.GetString("recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊 的當地語系化字串。
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 梯次 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_Batch {
            get {
                return ResourceManager.GetString("RegisterBookings_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行程景點:至少選擇1個!! 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CheckSelect {
            get {
                return ResourceManager.GetString("RegisterBookings_CheckSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出發航空 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT3 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出發航班 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT4 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出發日期 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT5 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回程航空 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT6 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回程航班 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT7 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回程日期 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_CONTENT8 {
            get {
                return ResourceManager.GetString("RegisterBookings_CONTENT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出發航班資訊 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_Departing {
            get {
                return ResourceManager.GetString("RegisterBookings_Departing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行程景點 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_DESCRIPTION {
            get {
                return ResourceManager.GetString("RegisterBookings_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 您的送客行程需至少包含一個新的景點。 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_DESCRIPTION_Hint {
            get {
                return ResourceManager.GetString("RegisterBookings_DESCRIPTION_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行程和送客名單 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_HPF {
            get {
                return ResourceManager.GetString("RegisterBookings_HPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 上傳的資料需包含航班訂購憑證或是機票憑證。 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_HPF_Hint {
            get {
                return ResourceManager.GetString("RegisterBookings_HPF_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ You will be able to register bookings once your participation of rewards program is confirmed by the organizer. 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_msg {
            get {
                return ResourceManager.GetString("RegisterBookings_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送客筆數 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_ORDER {
            get {
                return ResourceManager.GetString("RegisterBookings_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (不包含領隊) 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_ORDER_Hint {
            get {
                return ResourceManager.GetString("RegisterBookings_ORDER_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回程航班資訊 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_Returning {
            get {
                return ResourceManager.GetString("RegisterBookings_Returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 檔案格式僅支援 PDF 和 WORD 檔，大小要小於 5MB。 的當地語系化字串。
        /// </summary>
        public static string RegisterBookings_UploadLimit {
            get {
                return ResourceManager.GetString("RegisterBookings_UploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊 的當地語系化字串。
        /// </summary>
        public static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊日期 的當地語系化字串。
        /// </summary>
        public static string registered_date {
            get {
                return ResourceManager.GetString("registered_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動報名 的當地語系化字串。
        /// </summary>
        public static string registration_activity {
            get {
                return ResourceManager.GetString("registration_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已重覆 的當地語系化字串。
        /// </summary>
        public static string Repeated {
            get {
                return ResourceManager.GetString("Repeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *為必填欄位 的當地語系化字串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必填 的當地語系化字串。
        /// </summary>
        public static string Required2 {
            get {
                return ResourceManager.GetString("Required2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新輸入 的當地語系化字串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重設密碼 的當地語系化字串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認新密碼 的當地語系化字串。
        /// </summary>
        public static string ResetPassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不符 的當地語系化字串。
        /// </summary>
        public static string ResetPassword_NotMatch {
            get {
                return ResourceManager.GetString("ResetPassword_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;p&gt;您好 {0}，您的帳號為：{1}&lt;/p&gt;&lt;p&gt;請點擊連結進行帳戶開通：&lt;a href=&quot;{2}&quot; target=&quot;_blank&quot;&gt;點我開通&lt;/a&gt;&lt;/p&gt; 的當地語系化字串。
        /// </summary>
        public static string Rst_Body {
            get {
                return ResourceManager.GetString("Rst_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 菲律賓後台系統註冊確認信 的當地語系化字串。
        /// </summary>
        public static string Rst_Subject {
            get {
                return ResourceManager.GetString("Rst_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存檔 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string search1 {
            get {
                return ResourceManager.GetString("search1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋結果 的當地語系化字串。
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇問卷 的當地語系化字串。
        /// </summary>
        public static string SelectQuestionnaire {
            get {
                return ResourceManager.GetString("SelectQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 挑選使用者 的當地語系化字串。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送客人數排名表 的當地語系化字串。
        /// </summary>
        public static string SendGuestNumberList {
            get {
                return ResourceManager.GetString("SendGuestNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送客人數統計表 的當地語系化字串。
        /// </summary>
        public static string SendingGuestStatistics {
            get {
                return ResourceManager.GetString("SendingGuestStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者條款 的當地語系化字串。
        /// </summary>
        public static string servicepolicy {
            get {
                return ResourceManager.GetString("servicepolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示 的當地語系化字串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登 入 的當地語系化字串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登 出 的當地語系化字串。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始日 的當地語系化字串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統管理者 的當地語系化字串。
        /// </summary>
        public static string SysManager {
            get {
                return ResourceManager.GetString("SysManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標題 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;li class=&quot;go&quot;&gt;前往 {0} 頁 / 總共 {1} 頁&lt;/li&gt; 的當地語系化字串。
        /// </summary>
        public static string TotalPage {
            get {
                return ResourceManager.GetString("TotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者名稱 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者搜尋 的當地語系化字串。
        /// </summary>
        public static string UserSearch {
            get {
                return ResourceManager.GetString("UserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好康活動 的當地語系化字串。
        /// </summary>
        public static string view01 {
            get {
                return ResourceManager.GetString("view01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動日期 的當地語系化字串。
        /// </summary>
        public static string view02 {
            get {
                return ResourceManager.GetString("view02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 鄰近 的當地語系化字串。
        /// </summary>
        public static string view03 {
            get {
                return ResourceManager.GetString("view03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店家 的當地語系化字串。
        /// </summary>
        public static string view04 {
            get {
                return ResourceManager.GetString("view04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推薦行程 的當地語系化字串。
        /// </summary>
        public static string view05 {
            get {
                return ResourceManager.GetString("view05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 周邊 的當地語系化字串。
        /// </summary>
        public static string view06 {
            get {
                return ResourceManager.GetString("view06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 景點 的當地語系化字串。
        /// </summary>
        public static string view07 {
            get {
                return ResourceManager.GetString("view07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可累積 的當地語系化字串。
        /// </summary>
        public static string view08 {
            get {
                return ResourceManager.GetString("view08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 立即訂購 的當地語系化字串。
        /// </summary>
        public static string view09 {
            get {
                return ResourceManager.GetString("view09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額以付款頁面為準 的當地語系化字串。
        /// </summary>
        public static string view10 {
            get {
                return ResourceManager.GetString("view10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 集點獨享優惠 的當地語系化字串。
        /// </summary>
        public static string view11 {
            get {
                return ResourceManager.GetString("view11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 菲律賓後台系統 的當地語系化字串。
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taiwan Expert Rewards 的當地語系化字串。
        /// </summary>
        public static string WebsiteTitle_Web {
            get {
                return ResourceManager.GetString("WebsiteTitle_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hi, 的當地語系化字串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
