//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE_PLUG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICLE_PLUG()
        {
            this.ATTACHMENT = new HashSet<ATTACHMENT>();
            this.PARAGRAPH = new HashSet<PARAGRAPH>();
        }
    
        public string ID { get; set; }
        public string ARTICLE_ID { get; set; }
        public string ARTICLE_PLUG_TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATER { get; set; }
        public int ORDER { get; set; }
        public string CONTENT1 { get; set; }
        public string CONTENT2 { get; set; }
        public string CONTENT3 { get; set; }
        public string CONTENT4 { get; set; }
        public string CONTENT5 { get; set; }
        public string CONTENT6 { get; set; }
        public string CONTENT7 { get; set; }
        public string CONTENT8 { get; set; }
        public string CONTENT9 { get; set; }
        public string CONTENT10 { get; set; }
        public string CONTENT11 { get; set; }
        public string CONTENT12 { get; set; }
        public string CONTENT13 { get; set; }
        public string CONTENT14 { get; set; }
        public string CONTENT15 { get; set; }
        public string CONTENT16 { get; set; }
        public string CONTENT17 { get; set; }
        public string CONTENT18 { get; set; }
        public string CONTENT19 { get; set; }
        public string CONTENT20 { get; set; }
        public Nullable<decimal> DECIMAL1 { get; set; }
        public Nullable<decimal> DECIMAL2 { get; set; }
        public Nullable<decimal> DECIMAL3 { get; set; }
        public Nullable<decimal> DECIMAL4 { get; set; }
        public Nullable<decimal> DECIMAL5 { get; set; }
        public Nullable<System.DateTime> DATETIME1 { get; set; }
        public Nullable<System.DateTime> DATETIME2 { get; set; }
        public Nullable<System.DateTime> DATETIME3 { get; set; }
        public Nullable<System.DateTime> DATETIME4 { get; set; }
        public Nullable<System.DateTime> DATETIME5 { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACHMENT> ATTACHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAGRAPH> PARAGRAPH { get; set; }
    }
}
