//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHMENT
    {
        public string ID { get; set; }
        public string ATT_TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATER { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FILE_NAME { get; set; }
        public string ORIGINAL_FILE_NAME { get; set; }
        public string EXTENSION { get; set; }
        public string MAIN_ID { get; set; }
        public int ORDER { get; set; }
        public string CONTENT1 { get; set; }
        public string CONTENT2 { get; set; }
        public string CONTENT3 { get; set; }
        public string CONTENT4 { get; set; }
        public string CONTENT5 { get; set; }
        public string CONTENT6 { get; set; }
        public string CONTENT7 { get; set; }
        public string CONTENT8 { get; set; }
        public string CONTENT9 { get; set; }
        public string CONTENT10 { get; set; }
    
        public virtual MESSAGE MESSAGE { get; set; }
        public virtual SYSUSER SYSUSER { get; set; }
        public virtual USER USER { get; set; }
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual NODE NODE { get; set; }
        public virtual DATA1 DATA1 { get; set; }
        public virtual DATA2 DATA2 { get; set; }
        public virtual DATA3 DATA3 { get; set; }
        public virtual DATA4 DATA4 { get; set; }
        public virtual DATA5 DATA5 { get; set; }
        public virtual DATA6 DATA6 { get; set; }
        public virtual DATA7 DATA7 { get; set; }
        public virtual DATA8 DATA8 { get; set; }
        public virtual ARTICLE_PLUG ARTICLE_PLUG { get; set; }
        public virtual PLUS PLUS { get; set; }
    }
}
