//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA8
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATA8()
        {
            this.PLUS = new HashSet<PLUS>();
            this.ATTACHMENT = new HashSet<ATTACHMENT>();
            this.PARAGRAPH = new HashSet<PARAGRAPH>();
        }
    
        public string ID { get; set; }
        public string NODE_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATER { get; set; }
        public string DATA_TYPE { get; set; }
        public string STATUS { get; set; }
        public byte ENABLE { get; set; }
        public int ORDER { get; set; }
        public string CONTENT1 { get; set; }
        public string CONTENT2 { get; set; }
        public string CONTENT3 { get; set; }
        public string CONTENT4 { get; set; }
        public string CONTENT5 { get; set; }
        public string CONTENT6 { get; set; }
        public string CONTENT7 { get; set; }
        public string CONTENT8 { get; set; }
        public string CONTENT9 { get; set; }
        public string CONTENT10 { get; set; }
        public string CONTENT11 { get; set; }
        public string CONTENT12 { get; set; }
        public string CONTENT13 { get; set; }
        public string CONTENT14 { get; set; }
        public string CONTENT15 { get; set; }
        public string CONTENT16 { get; set; }
        public string CONTENT17 { get; set; }
        public string CONTENT18 { get; set; }
        public string CONTENT19 { get; set; }
        public string CONTENT20 { get; set; }
        public string CONTENT21 { get; set; }
        public string CONTENT22 { get; set; }
        public string CONTENT23 { get; set; }
        public string CONTENT24 { get; set; }
        public string CONTENT25 { get; set; }
        public string CONTENT26 { get; set; }
        public string CONTENT27 { get; set; }
        public string CONTENT28 { get; set; }
        public string CONTENT29 { get; set; }
        public string CONTENT30 { get; set; }
        public string CONTENT31 { get; set; }
        public string CONTENT32 { get; set; }
        public string CONTENT33 { get; set; }
        public string CONTENT34 { get; set; }
        public string CONTENT35 { get; set; }
        public string CONTENT36 { get; set; }
        public string CONTENT37 { get; set; }
        public string CONTENT38 { get; set; }
        public string CONTENT39 { get; set; }
        public string CONTENT40 { get; set; }
        public string CONTENT41 { get; set; }
        public string CONTENT42 { get; set; }
        public string CONTENT43 { get; set; }
        public string CONTENT44 { get; set; }
        public string CONTENT45 { get; set; }
        public string CONTENT46 { get; set; }
        public string CONTENT47 { get; set; }
        public string CONTENT48 { get; set; }
        public string CONTENT49 { get; set; }
        public string CONTENT50 { get; set; }
        public string CONTENT51 { get; set; }
        public string CONTENT52 { get; set; }
        public string CONTENT53 { get; set; }
        public string CONTENT54 { get; set; }
        public string CONTENT55 { get; set; }
        public string CONTENT56 { get; set; }
        public string CONTENT57 { get; set; }
        public string CONTENT58 { get; set; }
        public string CONTENT59 { get; set; }
        public string CONTENT60 { get; set; }
        public string CONTENT61 { get; set; }
        public string CONTENT62 { get; set; }
        public string CONTENT63 { get; set; }
        public string CONTENT64 { get; set; }
        public string CONTENT65 { get; set; }
        public string CONTENT66 { get; set; }
        public string CONTENT67 { get; set; }
        public string CONTENT68 { get; set; }
        public string CONTENT69 { get; set; }
        public string CONTENT70 { get; set; }
        public string CONTENT71 { get; set; }
        public string CONTENT72 { get; set; }
        public string CONTENT73 { get; set; }
        public string CONTENT74 { get; set; }
        public string CONTENT75 { get; set; }
        public string CONTENT76 { get; set; }
        public string CONTENT77 { get; set; }
        public string CONTENT78 { get; set; }
        public string CONTENT79 { get; set; }
        public string CONTENT80 { get; set; }
        public string CONTENT81 { get; set; }
        public string CONTENT82 { get; set; }
        public string CONTENT83 { get; set; }
        public string CONTENT84 { get; set; }
        public string CONTENT85 { get; set; }
        public string CONTENT86 { get; set; }
        public string CONTENT87 { get; set; }
        public string CONTENT88 { get; set; }
        public string CONTENT89 { get; set; }
        public string CONTENT90 { get; set; }
        public string CONTENT91 { get; set; }
        public string CONTENT92 { get; set; }
        public string CONTENT93 { get; set; }
        public string CONTENT94 { get; set; }
        public string CONTENT95 { get; set; }
        public string CONTENT96 { get; set; }
        public string CONTENT97 { get; set; }
        public string CONTENT98 { get; set; }
        public string CONTENT99 { get; set; }
        public string CONTENT100 { get; set; }
        public string CONTENT101 { get; set; }
        public string CONTENT102 { get; set; }
        public string CONTENT103 { get; set; }
        public string CONTENT104 { get; set; }
        public string CONTENT105 { get; set; }
        public string CONTENT106 { get; set; }
        public string CONTENT107 { get; set; }
        public string CONTENT108 { get; set; }
        public string CONTENT109 { get; set; }
        public string CONTENT110 { get; set; }
        public Nullable<decimal> DECIMAL1 { get; set; }
        public Nullable<decimal> DECIMAL2 { get; set; }
        public Nullable<decimal> DECIMAL3 { get; set; }
        public Nullable<decimal> DECIMAL4 { get; set; }
        public Nullable<decimal> DECIMAL5 { get; set; }
        public Nullable<decimal> DECIMAL6 { get; set; }
        public Nullable<decimal> DECIMAL7 { get; set; }
        public Nullable<decimal> DECIMAL8 { get; set; }
        public Nullable<decimal> DECIMAL9 { get; set; }
        public Nullable<decimal> DECIMAL10 { get; set; }
        public Nullable<decimal> DECIMAL11 { get; set; }
        public Nullable<decimal> DECIMAL12 { get; set; }
        public Nullable<decimal> DECIMAL13 { get; set; }
        public Nullable<decimal> DECIMAL14 { get; set; }
        public Nullable<decimal> DECIMAL15 { get; set; }
        public Nullable<decimal> DECIMAL16 { get; set; }
        public Nullable<decimal> DECIMAL17 { get; set; }
        public Nullable<decimal> DECIMAL18 { get; set; }
        public Nullable<decimal> DECIMAL19 { get; set; }
        public Nullable<decimal> DECIMAL20 { get; set; }
        public Nullable<decimal> DECIMAL21 { get; set; }
        public Nullable<decimal> DECIMAL22 { get; set; }
        public Nullable<decimal> DECIMAL23 { get; set; }
        public Nullable<decimal> DECIMAL24 { get; set; }
        public Nullable<decimal> DECIMAL25 { get; set; }
        public Nullable<decimal> DECIMAL26 { get; set; }
        public Nullable<decimal> DECIMAL27 { get; set; }
        public Nullable<decimal> DECIMAL28 { get; set; }
        public Nullable<decimal> DECIMAL29 { get; set; }
        public Nullable<decimal> DECIMAL30 { get; set; }
        public Nullable<decimal> DECIMAL31 { get; set; }
        public Nullable<decimal> DECIMAL32 { get; set; }
        public Nullable<decimal> DECIMAL33 { get; set; }
        public Nullable<decimal> DECIMAL34 { get; set; }
        public Nullable<decimal> DECIMAL35 { get; set; }
        public Nullable<decimal> DECIMAL36 { get; set; }
        public Nullable<decimal> DECIMAL37 { get; set; }
        public Nullable<decimal> DECIMAL38 { get; set; }
        public Nullable<decimal> DECIMAL39 { get; set; }
        public Nullable<decimal> DECIMAL40 { get; set; }
        public Nullable<decimal> DECIMAL41 { get; set; }
        public Nullable<decimal> DECIMAL42 { get; set; }
        public Nullable<decimal> DECIMAL43 { get; set; }
        public Nullable<decimal> DECIMAL44 { get; set; }
        public Nullable<decimal> DECIMAL45 { get; set; }
        public Nullable<decimal> DECIMAL46 { get; set; }
        public Nullable<decimal> DECIMAL47 { get; set; }
        public Nullable<decimal> DECIMAL48 { get; set; }
        public Nullable<decimal> DECIMAL49 { get; set; }
        public Nullable<decimal> DECIMAL50 { get; set; }
        public Nullable<decimal> DECIMAL51 { get; set; }
        public Nullable<decimal> DECIMAL52 { get; set; }
        public Nullable<decimal> DECIMAL53 { get; set; }
        public Nullable<decimal> DECIMAL54 { get; set; }
        public Nullable<decimal> DECIMAL55 { get; set; }
        public Nullable<decimal> DECIMAL56 { get; set; }
        public Nullable<decimal> DECIMAL57 { get; set; }
        public Nullable<decimal> DECIMAL58 { get; set; }
        public Nullable<decimal> DECIMAL59 { get; set; }
        public Nullable<decimal> DECIMAL60 { get; set; }
        public Nullable<decimal> DECIMAL61 { get; set; }
        public Nullable<decimal> DECIMAL62 { get; set; }
        public Nullable<decimal> DECIMAL63 { get; set; }
        public Nullable<decimal> DECIMAL64 { get; set; }
        public Nullable<decimal> DECIMAL65 { get; set; }
        public Nullable<decimal> DECIMAL66 { get; set; }
        public Nullable<decimal> DECIMAL67 { get; set; }
        public Nullable<decimal> DECIMAL68 { get; set; }
        public Nullable<decimal> DECIMAL69 { get; set; }
        public Nullable<decimal> DECIMAL70 { get; set; }
        public Nullable<decimal> DECIMAL71 { get; set; }
        public Nullable<decimal> DECIMAL72 { get; set; }
        public Nullable<decimal> DECIMAL73 { get; set; }
        public Nullable<decimal> DECIMAL74 { get; set; }
        public Nullable<decimal> DECIMAL75 { get; set; }
        public Nullable<decimal> DECIMAL76 { get; set; }
        public Nullable<decimal> DECIMAL77 { get; set; }
        public Nullable<decimal> DECIMAL78 { get; set; }
        public Nullable<decimal> DECIMAL79 { get; set; }
        public Nullable<decimal> DECIMAL80 { get; set; }
        public Nullable<decimal> DECIMAL81 { get; set; }
        public Nullable<decimal> DECIMAL82 { get; set; }
        public Nullable<decimal> DECIMAL83 { get; set; }
        public Nullable<decimal> DECIMAL84 { get; set; }
        public Nullable<decimal> DECIMAL85 { get; set; }
        public Nullable<decimal> DECIMAL86 { get; set; }
        public Nullable<decimal> DECIMAL87 { get; set; }
        public Nullable<decimal> DECIMAL88 { get; set; }
        public Nullable<decimal> DECIMAL89 { get; set; }
        public Nullable<decimal> DECIMAL90 { get; set; }
        public Nullable<decimal> DECIMAL91 { get; set; }
        public Nullable<decimal> DECIMAL92 { get; set; }
        public Nullable<decimal> DECIMAL93 { get; set; }
        public Nullable<decimal> DECIMAL94 { get; set; }
        public Nullable<decimal> DECIMAL95 { get; set; }
        public Nullable<decimal> DECIMAL96 { get; set; }
        public Nullable<decimal> DECIMAL97 { get; set; }
        public Nullable<decimal> DECIMAL98 { get; set; }
        public Nullable<decimal> DECIMAL99 { get; set; }
        public Nullable<decimal> DECIMAL100 { get; set; }
        public Nullable<decimal> DECIMAL101 { get; set; }
        public Nullable<decimal> DECIMAL102 { get; set; }
        public Nullable<decimal> DECIMAL103 { get; set; }
        public Nullable<decimal> DECIMAL104 { get; set; }
        public Nullable<decimal> DECIMAL105 { get; set; }
        public Nullable<decimal> DECIMAL106 { get; set; }
        public Nullable<decimal> DECIMAL107 { get; set; }
        public Nullable<decimal> DECIMAL108 { get; set; }
        public Nullable<decimal> DECIMAL109 { get; set; }
        public Nullable<decimal> DECIMAL110 { get; set; }
        public Nullable<System.DateTime> DATETIME1 { get; set; }
        public Nullable<System.DateTime> DATETIME2 { get; set; }
        public Nullable<System.DateTime> DATETIME3 { get; set; }
        public Nullable<System.DateTime> DATETIME4 { get; set; }
        public Nullable<System.DateTime> DATETIME5 { get; set; }
        public Nullable<System.DateTime> DATETIME6 { get; set; }
        public Nullable<System.DateTime> DATETIME7 { get; set; }
        public Nullable<System.DateTime> DATETIME8 { get; set; }
        public Nullable<System.DateTime> DATETIME9 { get; set; }
        public Nullable<System.DateTime> DATETIME10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLUS> PLUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACHMENT> ATTACHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAGRAPH> PARAGRAPH { get; set; }
    }
}
