//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICLE> ARTICLE { get; set; }
        public virtual DbSet<ARTICLE_PLUG> ARTICLE_PLUG { get; set; }
        public virtual DbSet<ATTACHMENT> ATTACHMENT { get; set; }
        public virtual DbSet<AUTHORITY> AUTHORITY { get; set; }
        public virtual DbSet<DATA1> DATA1 { get; set; }
        public virtual DbSet<DATA2> DATA2 { get; set; }
        public virtual DbSet<DATA3> DATA3 { get; set; }
        public virtual DbSet<DATA4> DATA4 { get; set; }
        public virtual DbSet<DATA5> DATA5 { get; set; }
        public virtual DbSet<DATA6> DATA6 { get; set; }
        public virtual DbSet<DATA7> DATA7 { get; set; }
        public virtual DbSet<DATA8> DATA8 { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_LOG> MESSAGE_LOG { get; set; }
        public virtual DbSet<NODE> NODE { get; set; }
        public virtual DbSet<PARAGRAPH> PARAGRAPH { get; set; }
        public virtual DbSet<PLUS> PLUS { get; set; }
        public virtual DbSet<ROLE_USER_MAPPING> ROLE_USER_MAPPING { get; set; }
        public virtual DbSet<SYSUSER> SYSUSER { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<ROLE_GROUP> ROLE_GROUP { get; set; }
        public virtual DbSet<COUNTER> COUNTER { get; set; }
    }
}
