//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingspModel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_USER_MAPPING
    {
        public string ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATER { get; set; }
        public string USER_ID { get; set; }
        public string ROLE_GROUP_ID { get; set; }
    
        public virtual SYSUSER SYSUSER { get; set; }
        public virtual USER USER { get; set; }
        public virtual ROLE_GROUP ROLE_GROUP { get; set; }
    }
}
